# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a4fd5b93add6277c5384bcbb2c826be84c4c59cebff61243ea4d35df4c702b57c107f8912b7aea8b3bcb423689508d6078a86776ae9982f6caae1b64189dde4

test:
  secret_key_base: b3e1bb3922b4d66930d0aaaa385edd8fd02c3b1d933b3156ebedde81ad3aab1ecdcb4bf48941f7c0aacfa847c66e2667cf54d8726147c6ecab3b3f312ceff947

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
