ALTER TABLE BOOK_ISSUE MODIFY COLUMN issue_date  TIMESTAMP NOT NULL DEFAULT NOW();

DELIMITER ;;
CREATE TRIGGER book_due_date BEFORE INSERT ON book_issue FOR EACH ROW
BEGIN
  SET NEW.due_date = DATE_ADD(NOW(), INTERVAL 15 DAY);
END;;
DELIMITER ;
