/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2015-10-26 07:08:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.Employee;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/view/header.jsp", Long.valueOf(1445238517381L));
    _jspx_dependants.put("/view/./master.jsp", Long.valueOf(1445229207483L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link href=\"view/css/custom.css\" rel=\"stylesheet\">\r\n");
      out.write("<title>Register Employee</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t<img src=\"./view/images/logo_meta.gif\"> \r\n");
      out.write("\t\t<h1>Metacube Software Pvt. Ltd.</h1>\r\n");
      out.write("\t\t<h3>Programmed for Excellence</h3>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"navigation\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"/MVC-Assignment-1/Home\">Home</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/MVC-Assignment-1/RegisterChangeUser\">New Register </a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/MVC-Assignment-1/FetchRecords\">Fetch All Records</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
 
		String id = "";
		String name = "";
		String email = "";
		String age = "";
		Employee emp = null;
		boolean readonly = false;
		
		if(request.getAttribute("readonly") != null) {
			readonly = (boolean)request.getAttribute("readonly");
		}
		
		if((Employee) request.getAttribute("employee") != null) {
			emp = (Employee) request.getAttribute("employee");
			id = emp.getId()+"";
			name = emp.getName();
			email = emp.getEmail();
			age = emp.getAge()+"";
		} else {
			id = request.getAttribute("employeeId")+"";
		}
	
      out.write("\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<form action=\"/MVC-Assignment-1/RegisterChangeUser\" method=\"post\">\r\n");
      out.write("\t\t\t\t<legend><h2>Register</h3></legend><hr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>Employee ID:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(id);
      out.write("<input type=\"hidden\" name=\"employeeId\"value=\"");
      out.print(id);
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>Enter Name:</td>\r\n");
      out.write("\t\t\t\t\t\t");
 if(!readonly){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"name\" placeholder=\"Enter Full Name\" value=");
      out.print(name);
      out.write(" ></td>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
} else {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(name);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>Email</td>\r\n");
      out.write("\t\t\t\t\t\t");
 if(!readonly){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"email\" name=\"email\" placeholder =\"Enter Email\" value=");
      out.print(email);
      out.write(" ></td>\r\n");
      out.write("\t\t\t\t\t\t");
 } else {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(email);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>Age</td>\r\n");
      out.write("\t\t\t\t\t\t");
 if(!readonly){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"number\" name=\"age\" placeholder=\"Enter Age\" value=");
      out.print(age);
      out.write("></td>\r\n");
      out.write("\t\t\t\t\t\t");
} else {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(age);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
if(!readonly) {
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td> <input type=\"submit\" value=\"Update / Create\" name=\"registerUser\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td> <input type=\"reset\" value=\"Reset\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
 } request.setAttribute("readonly", null);
      out.write("\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("\t<a href=\"#\">Link 1 |</a> <a href=\"#\">Link 2 |</a> <a href=\"#\">Link 3 |</a> <br> \r\n");
      out.write("\tCopyright © 2015. All rights Reserved\r\n");
      out.write("</footer>\r\n");
      out.write("\t\t");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
